# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Act')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Start_date', models.DateField(max_length=100)),
                ('End_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Registration_adress', models.CharField(max_length=200)),
                ('Office_adress', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=14)),
                ('Personal_Discount', models.IntegerField()),
                ('Software', models.CharField(max_length=40)),
                ('Mail', models.CharField(max_length=40)),
                ('Payment_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Start_date', models.DateField(max_length=100)),
                ('End_date', models.DateField(max_length=100)),
                ('Brief_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Brief')),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Payment_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Price_per_item', models.IntegerField()),
                ('Count_item', models.IntegerField()),
                ('Contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Birth_date', models.DateField(max_length=100)),
                ('Position', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Staff'),
        ),
        migrations.AddField(
            model_name='brief',
            name='Client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Staff'),
        ),
        migrations.AddField(
            model_name='act',
            name='Client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client'),
        ),
        migrations.AddField(
            model_name='act',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Staff'),
        ),
    ]
