# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 18:21
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Act')),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Start_date', models.DateField(max_length=100)),
                ('End_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Registration_adress', models.CharField(max_length=200)),
                ('Office_adress', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=24)),
                ('Personal_Discount', models.IntegerField()),
                ('Software', models.CharField(max_length=40)),
                ('Mail', models.CharField(max_length=40)),
                ('Payment_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=100)),
                ('Start_date', models.DateField(max_length=100)),
                ('End_date', models.DateField(max_length=100)),
                ('Brief_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Brief')),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Payment_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Birthday_date', models.DateField(max_length=100)),
                ('Position', models.CharField(default='Intern', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Price_per_item', models.IntegerField()),
                ('Count_item', models.IntegerField()),
                ('Contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Services',
            field=models.ManyToManyField(to='OnlineAgecy.Service'),
        ),
        migrations.AddField(
            model_name='brief',
            name='Client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
        migrations.AddField(
            model_name='act',
            name='Contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Contract'),
        ),
        migrations.AddField(
            model_name='act',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
    ]
