# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAgecy', '0002_auto_20170322_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Services',
            field=models.ManyToManyField(to='OnlineAgecy.Service'),
        ),
    ]
