# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAgecy', '0002_myuser_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Client'),
        ),
    ]
