# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAgecy', '0003_contract_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Birthday_date', models.DateField(max_length=100)),
            ],
        ),
    ]
