# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAgecy', '0004_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Position',
            field=models.CharField(default='Intern', max_length=40),
        ),
        migrations.AlterField(
            model_name='act',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Manager'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
