# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAgecy', '0005_auto_20170402_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='Client_id',
        ),
        migrations.AddField(
            model_name='act',
            name='Contract_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='OnlineAgecy.Contract'),
            preserve_default=False,
        ),
    ]
